version: "3.9"
services:
  app:
    build: .
    container_name: kds-backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=kds_db
    networks:
      - kds-network

  mysql:
    image: mysql:8
    container_name: kds-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kds_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kds-network

networks:
  kds-network:

volumes:
  mysql_data: