version: '3.8'
services:
  mysql:
    image: mysql:8.0 # เลือกเวอร์ชันที่ต้องการ
    container_name: kds_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password # กำหนดรหัสผ่าน root
      MYSQL_DATABASE: kds_db # กำหนดชื่อฐานข้อมูล
      MYSQL_USER: kds_user # กำหนดชื่อผู้ใช้
      MYSQL_PASSWORD: password # กำหนดรหัสผ่านของผู้ใช้
    ports:
      - '3366:3306' # แมปพอร์ต 3306 ของ local กับ container

volumes:
  mysql_data: